baseURL = 'https://cybecho.github.io/'
languageCode = 'ko-kr'
title = '삽질 저장소'
theme = 'hugo-blog-awesome'

[pagination]
  pagerSize = 20

enableRobotsTXT = true
enableEmoji = true

[params]
  [params.author]
    name = "Cybecho"
    avatar = "https://avatars.githubusercontent.com/u/42949995?v=4"

  title = "삽질 저장소"
  subtitle = "본질에 몰입하는 엔지니어 입니다. HW 및 OS에 관심이 많습니다."

  mainSections = ["posts"]
  postSectionName = "블로그"

  showToc = true
  TocOpen = false
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  UseHugoToc = true
  colorScheme = "auto"
  
[menu]
  [[menu.main]]
    identifier = "posts"
    name = "블로그"
    url = "/posts/"
    weight = 10
  [[menu.main]]
    identifier = "tags"
    name = "태그"
    url = "/tags/"
    weight = 20
  [[menu.main]]
    identifier = "series"
    name = "시리즈"
    url = "/series/"
    weight = 30
  [[menu.main]]
    identifier = "about"
    name = "소개"
    url = "/about/"
    weight = 40
  [[menu.main]]
    identifier = "archives"
    name = "아카이브"
    url = "/archives/"
    weight = 50

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    style = "github-dark"
    lineNos = true
    noClasses = false

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  series = 'series'
  tag = 'tags'
  archive = 'archives'

[build]
  writeStats = true
